export const LAST_UPDATED = "September 17, 2026";

// Legal copy rendered as static HTML inside the styled `.legal` container on
// the Privacy Policy page. Kept as a string so the long-form document stays
// readable and easy to update without fighting JSX escaping.
export const PRIVACY_POLICY_HTML = `
<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
<p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
<h2>Interpretation and Definitions</h2>
<h3>Interpretation</h3>
<p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<h3>Definitions</h3>
<p>For the purposes of this Privacy Policy:</p>
<ul>
<li>
<p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
</li>
<li>
<p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
</li>
<li>
<p><strong>API</strong> means the programmatic interfaces of the Service that developers call with a Personal Access Token.</p>
</li>
<li>
<p><strong>Application</strong> refers to the inklet Portal software provided by the Company that You install on a Device, including inklet Portal for macOS, inklet Portal for iOS, and their widgets and extensions.</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to inklet LLC, 119 S Western Ave Unit 1 #652 Chicago, IL 60612.</p>
</li>
<li>
<p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
</li>
<li>
<p><strong>Country</strong> refers to: Illinois,  United States</p>
</li>
<li>
<p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
</li>
<li>
<p><strong>Display</strong> means an inklet e-ink display paired with Your Account, or a Virtual Display You create in the Service.</p>
</li>
<li>
<p><strong>Personal Access Token</strong> (or &quot;PAT&quot;) means a credential You create in the Service to call the API or use the SDK on Your behalf.</p>
</li>
<li>
<p><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual.</p>
<p>We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</p>
</li>
<li>
<p><strong>SDK</strong> means the developer libraries the Company provides for building on the API, including the @inklethq/sdk package.</p>
</li>
<li>
<p><strong>Service</strong> refers to the Website, the Application, the API and SDK, and the cloud services that connect them to Your Displays, individually and together.</p>
</li>
<li>
<p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
</li>
<li>
<p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
</li>
<li>
<p><strong>User Content</strong> means the notes, text, links, images, PDFs, files and other material that You submit to the Service, whether from the Website, the Application, or through the API.</p>
</li>
<li>
<p><strong>Website</strong> refers to the inklet website, accessible from <a href="https://www.iminklet.com/">https://www.iminklet.com/</a>, the inklet Portal web app, accessible from <a href="https://portal.iminklet.com/">https://portal.iminklet.com/</a>, and their subdomains.</p>
</li>
<li>
<p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
</li>
</ul>
<h2>Collecting and Using Your Personal Data</h2>
<h3>Types of Data Collected</h3>
<h4>Personal Data</h4>
<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
<ul>
<li>Email address</li>
<li>Username and, if You sign in with a password, a hashed form of that password (We never store the password itself)</li>
<li>If You sign in with Google or Apple, the account identifier that provider gives Us for You and, for Apple, the token needed to revoke that sign-in when You delete Your Account</li>
<li>Billing records for a paid Subscription: Your Stripe customer and subscription identifiers, plan, billing interval, subscription status and period dates, and links to Your invoices</li>
<li>Personal Access Tokens You create for the API and SDK, stored in hashed form together with the name You give each token, its prefix and last four characters, and when it was last used</li>
</ul>
<h4>User Content</h4>
<p>The Service exists to keep and show what You send it. User Content You submit is stored on Our servers and includes:</p>
<ul>
<li>Notes and text You write or capture</li>
<li>Links You send, and the text and images of the pages behind them, which We fetch on Your behalf</li>
<li>Images, PDFs and other files You upload or select from Your photo library</li>
<li>What the Service derives from that content in order to operate: descriptions of images, extracted text, summaries, the layouts rendered for Your Displays, and the timeline of each AI run</li>
</ul>
<p>User Content may contain Personal Data about You or about other people. Please only submit content You have the right to share.</p>
<h4>Usage Data</h4>
<p>Usage Data is collected automatically when using the Service.</p>
<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
<p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>
<p>When You sign in, We record the session: the name of the Device or browser You signed in from, its IP address, and when the session was created and last active. You can see and revoke Your sessions from the Account page of the Service.</p>
<h4>Information Collected while Using the Application</h4>
<p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
<ul>
<li>
<p><strong>Your approximate location</strong>, to show local weather on the Home screen. On iOS the coordinates are sent to Apple Weather (WeatherKit); on macOS they are sent to Open-Meteo. In both cases the request goes directly from Your Device to the weather provider. Your location is not sent to or stored on Our servers.</p>
</li>
<li>
<p><strong>Your camera</strong>, on iOS, only to scan the pairing code on a Display. The camera feed is processed on Your Device and is not uploaded.</p>
</li>
<li>
<p><strong>Pictures from Your photo library</strong> that You choose to send to a Display. Only the pictures You select are uploaded.</p>
</li>
<li>
<p><strong>What You have in front of You</strong>, on macOS, when You summon the composer with the keyboard shortcut or the Services menu: the address of the page open in Your browser, the text You have selected, a file selected in Finder, an image You have open, or the contents of Your clipboard. The Application reads this through macOS automation (Apple Events) and the pasteboard only at that moment, offers it to You in the composer, and sends it to Our servers only if You choose to send it.</p>
</li>
</ul>
<p>We use this information to provide features of Our Service, to improve and customize Our Service. Content You choose to send is uploaded to the Company's servers and handled as User Content; the rest stays on Your Device.</p>
<p>The Application stores Your sign-in tokens in the operating system's Keychain on macOS and iOS. The macOS Application also checks for updates against Our update feed hosted on GitHub, which receives Your IP address and the Application version when it does.</p>
<p>You can enable or disable access to this information at any time, through Your Device settings.</p>
<h4>Information from Your Displays</h4>
<p>When You pair an inklet Display with Your Account, the Display connects to Our servers and reports what We need to operate it: its hardware identifier, firmware version, battery level and charging state, whether it is online and when it was last seen, which image it has confirmed showing, and its current state. We also record the nickname You give it and when it was paired. A Virtual Display reports its canvas size and what it last rendered.</p>
<h4>Tracking Technologies and Cookies</h4>
<p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:</p>
<ul>
<li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
<li><strong>Local storage.</strong> The inklet Portal web app keeps Your sign-in tokens in Your browser's local storage rather than in Cookies, so that You stay signed in between visits. Signing out clears them.</li>
<li><strong>Analytics scripts.</strong> Our marketing website loads scripts from Google Analytics and Vercel Analytics that measure page views and how visitors move through the site. The inklet Portal web app does not load analytics scripts.</li>
</ul>
<p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
<p>Where required by law, we use non-essential cookies (such as analytics cookies) only with Your consent. You can withdraw or change Your consent at any time through Your browser or device settings, including by blocking or deleting Cookies. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
<p>We use the following kinds of Cookies and similar technologies:</p>
<ul>
<li>
<p><strong>Necessary / Essential</strong></p>
<p>Type: Session Cookies and browser local storage</p>
<p>Administered by: Us</p>
<p>Purpose: These are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without them, the services that You have asked for cannot be provided, and We only use them to provide You with those services.</p>
</li>
<li>
<p><strong>Functionality</strong></p>
<p>Type: Persistent Cookies</p>
<p>Administered by: Us</p>
<p>Purpose: These allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
</li>
<li>
<p><strong>Analytics / Performance</strong></p>
<p>Type: Persistent Cookies and scripts</p>
<p>Administered by: Google (Google Analytics) and Vercel (Vercel Analytics), on Our marketing website only</p>
<p>Purpose: These help Us understand how visitors use the marketing website, for example which pages are visited and from where, so that We can improve it. Google's privacy policy is at <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a> and Vercel's is at <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">https://vercel.com/legal/privacy-policy</a>.</p>
</li>
</ul>
<h3>Use of Your Personal Data</h3>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
<li>
<p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
</li>
<li>
<p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
</li>
<li>
<p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
</li>
<li>
<p><strong>To contact You:</strong> To contact You by email or by notices within the Service regarding updates or informative communications related to the functionalities, products or contracted services, including security updates, when necessary or reasonable for their implementation.</p>
</li>
<li>
<p><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</p>
</li>
<li>
<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
</li>
<li>
<p><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
</li>
<li>
<p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
</li>
</ul>
<p>We may share Your Personal Data in the following situations:</p>
<ul>
<li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to host and operate the Service, to process Your User Content, to process payments, to monitor and analyze the use of Our Service, and to contact You, as listed under Service Providers We Use below.</li>
<li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
<li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
<li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
<li><strong>With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
<li><strong>With Your consent</strong>: We may disclose Your Personal Data for any other purpose with Your consent.</li>
</ul>
<h3>AI Processing of Your User Content</h3>
<p>When You ask the Service to make a card, to summarize Your recent notes, or to let inklet choose a Display, an automated agent reads the User Content involved, fetches the pages behind any links, describes any images, picks a layout, and renders it for the Display. To do this, We send the relevant User Content to third-party AI model providers acting on Our behalf, currently Anthropic and OpenAI, and We send link addresses to Firecrawl, which fetches the page content for Us. These providers process the content only to return a result to Us, and under their API terms they do not use content sent through the API to train their models. We do not use Your User Content to train models of Our own.</p>
<p>Uploading content without asking for a card, and showing a picture as-is, do not involve AI processing. The output of each AI run, including its timeline, is stored with Your Account so that You can see what the agent did.</p>
<h3>Service Providers We Use</h3>
<p>We share Personal Data with the following categories of Service Providers, each bound to process it only on Our instructions:</p>
<ul>
<li><strong>Hosting and infrastructure:</strong> Amazon Web Services, for server hosting, file storage, content delivery, message queues, and the connection between Our servers and Your Displays; Vercel, for hosting the marketing website.</li>
<li><strong>AI model providers:</strong> Anthropic and OpenAI, as described above.</li>
<li><strong>Link retrieval:</strong> Firecrawl, which fetches the pages behind links You send.</li>
<li><strong>Payments:</strong> Stripe, as described under Payments below.</li>
<li><strong>Sign-in:</strong> Google and Apple, when You choose to sign in with them.</li>
<li><strong>Analytics:</strong> Google Analytics and Vercel Analytics, on the marketing website.</li>
<li><strong>Software distribution:</strong> GitHub, which hosts the macOS Application downloads and its update feed.</li>
<li><strong>Fonts:</strong> the inklet Portal web app loads fonts from Google Fonts, which receives Your IP address when the fonts are requested.</li>
<li><strong>Weather:</strong> Apple Weather on iOS and Open-Meteo on macOS, which receive Your approximate location directly from Your Device, as described above.</li>
</ul>
<h3>Retention of Your Personal Data</h3>
<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p>Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods (&quot;up to&quot;) and We may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>
<ul>
<li>
<p>Account Information</p>
<ul>
<li>Account details (email, username, sign-in method, billing records): retained for as long as Your Account exists. When You delete Your Account, We delete the Account and everything stored under it, cancel any Stripe subscription, and revoke Your Sign in with Apple grant. Stripe keeps the invoice records it is required to retain by law.</li>
<li>Sign-in sessions: retained until You sign out or revoke them, or until they expire.</li>
<li>Personal Access Tokens: retained until You revoke them or delete Your Account.</li>
</ul>
</li>
<li>
<p>User Content</p>
<ul>
<li>Notes, links, images, PDFs and files You send: retained until You delete them or delete Your Account.</li>
<li>Files You delete: removed from active storage promptly and purged from Our systems within 7 days.</li>
<li>AI runs: the timeline of each run is kept with Your Account; its detailed step logs are deleted after 30 days.</li>
</ul>
</li>
<li>
<p>Display Information</p>
<ul>
<li>Display status and history: retained while the Display is paired with Your Account, and deleted when You delete Your Account.</li>
</ul>
</li>
<li>
<p>Customer Support Data</p>
<ul>
<li>Support correspondence: up to 24 months from the date the matter is closed, to resolve follow-up inquiries, track service quality, and defend against potential legal claims.</li>
</ul>
</li>
<li>
<p>Usage Data</p>
<ul>
<li>
<p>Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection, which allows us to analyze trends while respecting privacy principles.</p>
</li>
<li>
<p>Plan usage counters (for example, images delivered per day): kept per period and reset as each period ends.</p>
</li>
<li>
<p>Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.</p>
</li>
</ul>
</li>
</ul>
<p>Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance.</p>
<p>We may retain Personal Data beyond the periods stated above for different reasons:</p>
<ul>
<li>Legal obligation: We are required by law to retain specific data (e.g., financial records for tax authorities).</li>
<li>Legal claims: Data is necessary to establish, exercise, or defend legal claims.</li>
<li>Your explicit request: You ask Us to retain specific information.</li>
<li>Technical limitations: Data exists in backup systems that are scheduled for routine deletion.</li>
</ul>
<p>You may request information about how long We will retain Your Personal Data by contacting Us.</p>
<p>When retention periods expire, We securely delete or anonymize Personal Data according to the following procedures:</p>
<ul>
<li>Deletion: Personal Data is removed from Our systems and no longer actively processed.</li>
<li>Backup retention: Residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule and are not restored except where necessary for security, disaster recovery, or legal compliance.</li>
<li>Anonymization: In some cases, We convert Personal Data into anonymous statistical data that cannot be linked back to You. This anonymized data may be retained indefinitely for research and analytics.</li>
</ul>
<h3>Transfer of Your Personal Data</h3>
<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
<p>Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
<h3>Delete Your Personal Data</h3>
<p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
<p>You can delete individual items of User Content, unpair Displays, and revoke sessions and Personal Access Tokens from within the Service. You can delete Your Account, and everything stored under it, from within the Service or by contacting Us by email. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>
<p>Deleting Your Account permanently removes Your User Content, Displays, tokens and sessions from Our systems, cancels any active Subscription, and revokes Your Sign in with Apple grant. Residual copies may remain in encrypted backups for a limited period, as described under Retention.</p>
<p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
<h3>Disclosure of Your Personal Data</h3>
<h4>Business Transactions</h4>
<p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
<h4>Law enforcement</h4>
<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
<h4>Other legal requirements</h4>
<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
<li>Comply with a legal obligation</li>
<li>Protect and defend the rights or property of the Company</li>
<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
<li>Protect the personal safety of Users of the Service or the public</li>
<li>Protect against legal liability</li>
</ul>
<h2>Payments</h2>
<p>We offer a paid Subscription, inklet Portal Pro, within the Service. Payment processing is handled by Stripe. When You subscribe, You are taken to a checkout page hosted by Stripe; when You change Your payment method, download invoices, or cancel, You are taken to a billing portal hosted by Stripe.</p>
<p>We will not store or collect Your payment card details. That information is provided directly to Stripe, whose use of Your personal information is governed by its Privacy Policy. Stripe adheres to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
<p>What We keep on Our side is the link between Your Account and Stripe: Your Stripe customer and subscription identifiers, the plan and billing interval You chose, the subscription status and period dates Stripe reports to Us, and links to Your invoices, so that the Service can show Your plan and payment history. Stripe receives Your email address and Account identifier so that it can match payments to You.</p>
<ul>
<li>
<p><strong>Stripe</strong></p>
<p>Their Privacy Policy can be viewed at <a href="https://stripe.com/us/privacy" target="_blank" rel="noopener noreferrer">https://stripe.com/us/privacy</a></p>
</li>
</ul>
<h2>GDPR Privacy Policy</h2>
<h3>Legal Basis for Processing Personal Data under GDPR</h3>
<p>We may process Personal Data under the following conditions:</p>
<ul>
<li><strong>Consent:</strong> You have given Your consent for processing Personal Data for one or more specific purposes.</li>
<li><strong>Performance of a contract:</strong> Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.</li>
<li><strong>Legal obligations:</strong> Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.</li>
<li><strong>Vital interests:</strong> Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.</li>
<li><strong>Public interests:</strong> Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.</li>
<li><strong>Legitimate interests:</strong> Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.</li>
</ul>
<p>In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.</p>
<h3>Your Rights under the GDPR</h3>
<p>The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise Your rights.</p>
<p>You have the right under this Privacy Policy, and by law if You are within the EU, to:</p>
<ul>
<li><strong>Request access to Your Personal Data.</strong> The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these actions yourself, please contact Us to assist You. This also enables You to receive a copy of the Personal Data We hold about You.</li>
<li><strong>Request correction of the Personal Data that We hold about You.</strong> You have the right to have any incomplete or inaccurate information We hold about You corrected.</li>
<li><strong>Object to processing of Your Personal Data.</strong> This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.</li>
<li><strong>Request erasure of Your Personal Data.</strong> You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.</li>
<li><strong>Request the transfer of Your Personal Data.</strong> We will provide to You, or to a third-party You have chosen, Your Personal Data in a structured, commonly used, machine-readable format. Please note that this right only applies to automated information which You initially provided consent for Us to use or where We used the information to perform a contract with You.</li>
<li><strong>Withdraw Your consent.</strong> You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be able to provide You with access to certain specific functionalities of the Service.</li>
</ul>
<h3>Exercising of Your GDPR Data Protection Rights</h3>
<p>You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note that we may ask You to verify Your identity before responding to such requests. If You make a request, We will try our best to respond to You as soon as possible.</p>
<p>You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.</p>
<h2>CCPA and CPRA Privacy Notice</h2>
<p>This privacy notice section for California residents supplements the information contained in Our Privacy Policy and it applies solely to all visitors, users, and others who reside in the State of California.</p>
<h3>Your Rights under the CCPA and CPRA</h3>
<p>The CCPA and CPRA provide California residents with specific rights regarding their personal information. If You are a resident of California, You have the following rights:</p>
<ul>
<li><strong>The right to notice.</strong> You have the right to be notified which categories of Personal Data are being collected and the purposes for which the Personal Data is being used.</li>
<li><strong>The right to request.</strong> Under CCPA and CPRA, You have the right to request that We disclose information to You about Our collection, use, sale, disclosure for business purposes and share of personal information. Once We receive and confirm Your request, We will disclose to You:
<ul>
<li>The categories of personal information We collected about You</li>
<li>The categories of sources for the personal information We collected about You</li>
<li>Our business or commercial purpose for collecting or selling that personal information</li>
<li>The categories of third parties with whom We share that personal information</li>
<li>The specific pieces of personal information We collected about You</li>
<li>If we sold Your personal information or disclosed Your personal information for a business purpose, We will disclose to You:
<ul>
<li>The categories of personal information categories sold</li>
<li>The categories of personal information categories disclosed</li>
</ul>
</li>
</ul>
</li>
<li><strong>The right to say no to the sale or sharing of Personal Data (opt-out).</strong> You have the right to direct Us to not sell Your personal information. To submit an opt-out request please contact Us.</li>
<li><strong>The right to correct Personal Data.</strong> You have the right to correct or rectify any inaccurate personal information about You that We maintain. Once We receive and confirm Your request, We will use commercially reasonable efforts to correct (and direct our Service Providers to correct) Your personal information.</li>
<li><strong>The right to limit use and disclosure of sensitive Personal Data.</strong> You have the right to request to limit the use or disclosure of certain sensitive personal information We collected about You, unless an exception applies.</li>
<li><strong>The right to delete Personal Data.</strong> You have the right to request the deletion of Your Personal Data, subject to certain exceptions. Once We receive and confirm Your request, We will delete (and direct Our Service Providers to delete) Your personal information from our records, unless an exception applies.</li>
<li><strong>The right not to be discriminated against.</strong> You have the right not to be discriminated against for exercising any of Your consumer's rights.</li>
</ul>
<h3>Exercising Your CCPA and CPRA Data Protection Rights</h3>
<p>In order to exercise any of Your rights under the CCPA and CPRA, and if You are a California resident, You can contact Us:</p>
<ul>
<li>By email: core@iminklet.com</li>
</ul>
<p>Only You, or a person registered with the California Secretary of State that You authorize to act on Your behalf, may make a verifiable request related to Your personal information.</p>
<p>Your request to Us must:</p>
<ul>
<li>Provide sufficient information that allows Us to reasonably verify You are the person about whom We collected personal information or an authorized representative</li>
<li>Describe Your request with sufficient detail that allows Us to properly understand, evaluate, and respond to it</li>
</ul>
<p>We cannot respond to Your request or provide You with the required information if We cannot:</p>
<ul>
<li>Verify Your identity or authority to make the request</li>
<li>And confirm that the personal information relates to You</li>
</ul>
<h2>&quot;Do Not Track&quot; Policy as Required by California Online Privacy Protection Act (CalOPPA)</h2>
<p>Our Service does not respond to Do Not Track signals.</p>
<p>However, some third party websites do keep track of Your browsing activities. If You are visiting such websites, You can set Your preferences in Your web browser to inform websites that You do not want to be tracked. You can enable or disable DNT by visiting the preferences or settings page of Your web browser.</p>
<h3>Security of Your Personal Data</h3>
<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
<h2>Children's Privacy</h2>
<p>Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 18 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
<h2>Links to Other Websites</h2>
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
<h2>Changes to this Privacy Policy</h2>
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p>For material changes, We will post a prominent notice on Our Service and, where We are able to, also let You know by email, prior to the change becoming effective, and We will update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
<h2>Contact Us</h2>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
<li>By email: <a href="mailto:core@iminklet.com">core@iminklet.com</a></li>
</ul>
`;
